project_id = "nrvetokwxizkannzhzvn"

[functions.ai-research]
verify_jwt = false

[functions.improve-prompt]
verify_jwt = false

[functions.refine-prompt]
verify_jwt = false

[functions.calendly-webhook]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.calcom-webhook]
verify_jwt = false

[functions.calcom-booking-fields]
verify_jwt = false
