import React, { useState, useEffect, useRef } from 'react';
import { Contact, CustomContactField, CompanyField } from '@/types/contact';
import { Phone, Mail, Globe, ExternalLink, Copy, Check, Building2, User, ChevronDown, Trash2, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from '@/hooks/use-toast';
import { useCustomFields } from '@/hooks/useCustomFields';
import { useCompanyFields } from '@/hooks/useCompanyFields';
import { useCompanyData } from '@/hooks/useCompanyData';
import { useAIResearch } from '@/hooks/useAIResearch';
import { AIResearchBox } from '@/components/AIResearchBox';
import { InlineEditField } from '@/components/InlineEditField';
import { LinkedContacts } from '@/components/LinkedContacts';
import { ContactHistoryBar } from '@/components/ContactHistoryBar';
import { ScriptSelector } from '@/components/ScriptSelector';
import { supabase } from '@/integrations/supabase/client';
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { toast as sonnerToast } from 'sonner';
import { useAutoGenerateSettings } from '@/hooks/useAutoGenerateSettings';
import { StaticScriptCard } from '@/components/StaticScriptCard';
import { useContactCardSectionOrder, SectionKey } from '@/hooks/useContactCardSectionOrder';

interface ContactCardProps {
  contact: Contact;
  onUpdate?: (updates: Partial<Contact>) => void;
  onSelectContact?: (contactId: string) => void;
  onDelete?: (contactId: string) => Promise<boolean>;
}

interface AICache {
  ai_summary?: string | null;
  ai_summary_updated_at?: string | null;
  ai_custom_research?: string | null;
  ai_custom_updated_at?: string | null;
}

export function ContactCard({ contact, onUpdate, onSelectContact, onDelete }: ContactCardProps) {
  const [editingField, setEditingField] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const { fields: customFields } = useCustomFields();
  const { fields: companyFields } = useCompanyFields();
  const { getCompanyFieldValues, updateCompanyData } = useCompanyData();
  const { isResearching, researchCompany, researchCompanyCustom, researchPersona } = useAIResearch();
  const { settings: autoGenSettings } = useAutoGenerateSettings();
  const { sectionOrder, sectionExpandedDefaults } = useContactCardSectionOrder();

  // AI Research state
  const [companyAI, setCompanyAI] = useState<AICache>({});
  const [contactPersona, setContactPersona] = useState<string | null>(null);
  const [personaUpdatedAt, setPersonaUpdatedAt] = useState<string | null>(null);
  const [hasCompanyResearch, setHasCompanyResearch] = useState(false);
  const [hasContactPersona, setHasContactPersona] = useState(false);
  
  // AI Script state
  const [aiScript, setAiScript] = useState<string | null>(null);
  const [aiScriptUpdatedAt, setAiScriptUpdatedAt] = useState<string | null>(null);
  const [isGeneratingScript, setIsGeneratingScript] = useState(false);
  const [selectedScriptId, setSelectedScriptId] = useState<string | null>(null);
  
  // Auto-generate state
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [autoGenProgress, setAutoGenProgress] = useState<string | null>(null);
  const autoGeneratedContactsRef = useRef<Set<string>>(new Set());
  const [dataLoaded, setDataLoaded] = useState(false);
  
  // Smart dependency state - tracks what the prompt requires
  const [promptDependencies, setPromptDependencies] = useState<{
    needsCompanyResearch: boolean;
    needsContactPersona: boolean;
  }>({ needsCompanyResearch: false, needsContactPersona: false });

  const activeCustomFields = customFields.filter(f => !f.isArchived).sort((a, b) => a.order - b.order);
  const activeCompanyFields = companyFields.filter(f => !f.isArchived).sort((a, b) => a.order - b.order);
  const companyFieldValues = contact.company ? getCompanyFieldValues(contact.company) : {};

  // Fetch prompt dependencies on mount
  useEffect(() => {
    const checkPromptDependencies = async () => {
      const { data: prompt } = await supabase
        .from('ai_prompts')
        .select('prompt')
        .eq('prompt_type', 'company_custom')
        .single();
      
      if (prompt) {
        setPromptDependencies({
          needsCompanyResearch: prompt.prompt.includes('{company_research}'),
          needsContactPersona: prompt.prompt.includes('{contact_persona}'),
        });
      }
    };
    checkPromptDependencies();
  }, []);

  // Load AI research data on mount or contact change (NO auto-research)
  useEffect(() => {
    const loadAIData = async () => {
      // Reset dataLoaded when contact changes
      setDataLoaded(false);
      
      // Load company AI data
      if (contact.company) {
        const { data: companyResult } = await supabase
          .from('company_data')
          .select('ai_summary, ai_summary_updated_at, ai_custom_research, ai_custom_updated_at')
          .eq('company_name', contact.company)
          .single();

        if (companyResult) {
          setCompanyAI(companyResult);
          setHasCompanyResearch(Boolean(companyResult.ai_summary));
        } else {
          setCompanyAI({});
          setHasCompanyResearch(false);
        }
      } else {
        setHasCompanyResearch(false);
      }

      // Load contact persona from the contact itself
      const { data: contactResult } = await supabase
        .from('contacts')
        .select('ai_persona, ai_persona_updated_at, ai_script, ai_script_updated_at')
        .eq('id', contact.id)
        .single();

      if (contactResult) {
        setContactPersona(contactResult.ai_persona);
        setPersonaUpdatedAt(contactResult.ai_persona_updated_at);
        setHasContactPersona(Boolean(contactResult.ai_persona));
        setAiScript(contactResult.ai_script);
        setAiScriptUpdatedAt(contactResult.ai_script_updated_at);
      } else {
        setHasContactPersona(false);
        setAiScript(null);
        setAiScriptUpdatedAt(null);
      }
      
      // Mark data as loaded after fetching
      setDataLoaded(true);
    };

    loadAIData();
  }, [contact.id, contact.company]);

  const handleRefreshCompanySearch = async () => {
    if (!contact.company) return;
    const result = await researchCompany(contact.company, contact.website);
    if (result) {
      setCompanyAI(prev => ({
        ...prev,
        ai_summary: result,
        ai_summary_updated_at: new Date().toISOString()
      }));
      setHasCompanyResearch(true); // Enable targeted research after company research is done
    }
  };

  const handleRefreshCustomResearch = async () => {
    if (!contact.company) return;
    const result = await researchCompanyCustom(contact.company, contact.website);
    if (result) {
      setCompanyAI(prev => ({
        ...prev,
        ai_custom_research: result,
        ai_custom_updated_at: new Date().toISOString()
      }));
    }
  };

  const handleRefreshPersona = async () => {
    const result = await researchPersona(contact);
    if (result) {
      setContactPersona(result);
      setPersonaUpdatedAt(new Date().toISOString());
      setHasContactPersona(true); // Enable targeted research if persona is required
    }
  };

  const handleGenerateScript = async (scriptId?: string) => {
    setIsGeneratingScript(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-script', {
        body: { contact_id: contact.id, script_id: scriptId || selectedScriptId }
      });

      if (error) throw error;
      if (data.error) throw new Error(data.error);

      setAiScript(data.script);
      setAiScriptUpdatedAt(data.timestamp);
      
      // If dependencies were auto-generated, update local state
      if (data.autoGenerated?.companyResearch) {
        // Refetch company research
        const { data: companyResult } = await supabase
          .from('company_data')
          .select('ai_summary, ai_summary_updated_at')
          .eq('company_name', contact.company)
          .single();
        if (companyResult) {
          setCompanyAI(prev => ({
            ...prev,
            ai_summary: companyResult.ai_summary,
            ai_summary_updated_at: companyResult.ai_summary_updated_at,
          }));
          setHasCompanyResearch(true);
        }
      }
      if (data.autoGenerated?.persona) {
        // Refetch persona
        const { data: contactResult } = await supabase
          .from('contacts')
          .select('ai_persona, ai_persona_updated_at')
          .eq('id', contact.id)
          .single();
        if (contactResult) {
          setContactPersona(contactResult.ai_persona);
          setPersonaUpdatedAt(contactResult.ai_persona_updated_at);
          setHasContactPersona(true);
        }
      }
      
      sonnerToast.success('Script generated');
    } catch (error) {
      console.error('Script generation error:', error);
      sonnerToast.error('Failed to generate script');
    } finally {
      setIsGeneratingScript(false);
    }
  };

  // Auto-generate logic - runs once per contact when they have no AI data
  useEffect(() => {
    const runAutoGenerate = async () => {
      // Skip if data hasn't loaded yet, settings not loaded, or auto-gen disabled
      if (!dataLoaded || !autoGenSettings || !autoGenSettings.enabled) return;
      
      // Skip if we've already auto-generated for this contact
      if (autoGeneratedContactsRef.current.has(contact.id)) return;
      
      // Check if contact has any existing AI data
      const hasExistingData = companyAI.ai_summary || contactPersona || companyAI.ai_custom_research || aiScript;
      if (hasExistingData) {
        autoGeneratedContactsRef.current.add(contact.id);
        return;
      }

      // Mark as processed for this contact
      autoGeneratedContactsRef.current.add(contact.id);
      setIsAutoGenerating(true);

      try {
        const steps: { key: keyof typeof autoGenSettings; label: string; fn: () => Promise<any> }[] = [];
        
        if (autoGenSettings.company_research && contact.company) {
          steps.push({ key: 'company_research', label: 'Company Research', fn: handleRefreshCompanySearch });
        }
        if (autoGenSettings.contact_persona) {
          steps.push({ key: 'contact_persona', label: 'Contact Persona', fn: handleRefreshPersona });
        }
        if (autoGenSettings.targeted_research && contact.company) {
          steps.push({ key: 'targeted_research', label: 'Targeted Research', fn: handleRefreshCustomResearch });
        }
        if (autoGenSettings.script_generation) {
          steps.push({ key: 'script_generation', label: 'AI Script', fn: () => handleGenerateScript() });
        }

        for (let i = 0; i < steps.length; i++) {
          const step = steps[i];
          setAutoGenProgress(`Auto-generating ${step.label}... (${i + 1}/${steps.length})`);
          await step.fn();
        }

        if (steps.length > 0) {
          sonnerToast.success(`Auto-generated ${steps.length} AI features`);
        }
      } catch (error) {
        console.error('Auto-generate error:', error);
      } finally {
        setIsAutoGenerating(false);
        setAutoGenProgress(null);
      }
    };

    // Small delay to ensure UI is ready
    const timer = setTimeout(runAutoGenerate, 300);
    return () => clearTimeout(timer);
  }, [contact.id, dataLoaded, autoGenSettings]);

  // Compute smart dependency disabled state
  const targetedResearchDisabled = 
    (promptDependencies.needsCompanyResearch && !hasCompanyResearch) ||
    (promptDependencies.needsContactPersona && !hasContactPersona);

  // Build disabled reason message
  const getDisabledReason = (): string | undefined => {
    const missing: string[] = [];
    if (promptDependencies.needsCompanyResearch && !hasCompanyResearch) {
      missing.push('Company Research');
    }
    if (promptDependencies.needsContactPersona && !hasContactPersona) {
      missing.push('Persona');
    }
    return missing.length > 0 ? `Run ${missing.join(' and ')} first` : undefined;
  };

  const copyToClipboard = async (value: string, fieldName: string) => {
    await navigator.clipboard.writeText(value);
    setCopiedField(fieldName);
    toast({ title: 'Copied to clipboard', duration: 1500 });
    setTimeout(() => setCopiedField(null), 1500);
  };

  const openGmail = () => {
    window.open(`https://mail.google.com/mail/?view=cm&to=${encodeURIComponent(contact.email)}`, '_blank');
  };

  const startEditing = (field: string, value: string) => {
    setEditingField(field);
    setEditValue(value);
  };

  const saveField = (field: string) => {
    if (onUpdate) {
      onUpdate({ [field]: editValue });
    }
    setEditingField(null);
  };

  const saveCustomField = (fieldId: string) => {
    if (onUpdate) {
      onUpdate({ 
        customFields: { 
          ...contact.customFields, 
          [fieldId]: editValue 
        } 
      });
    }
    setEditingField(null);
  };

  const saveCompanyField = (fieldId: string) => {
    if (contact.company) {
      updateCompanyData(contact.company, fieldId, editValue);
      toast({ title: 'Company data updated', description: 'Applied to all contacts at this company', duration: 2000 });
    }
    setEditingField(null);
  };

  const formatCallbackDate = (date: Date) => {
    return new Date(date).toLocaleString([], { 
      dateStyle: 'medium', 
      timeStyle: 'short' 
    });
  };

  const getCustomFieldValue = (field: CustomContactField): string => {
    const value = contact.customFields?.[field.id];
    if (value === undefined || value === null) return '';
    if (Array.isArray(value)) return value.join(', ');
    return String(value);
  };

  const getCompanyFieldValue = (field: CompanyField): string => {
    const value = companyFieldValues[field.id];
    if (value === undefined || value === null) return '';
    if (Array.isArray(value)) return value.join(', ');
    return String(value);
  };

  const renderFieldInput = (field: CustomContactField | CompanyField, isCompany: boolean) => {
    const value = editValue;

    switch (field.type) {
      case 'dropdown':
        return (
          <Select value={value} onValueChange={setEditValue}>
            <SelectTrigger className="h-7 text-sm">
              <SelectValue placeholder="Select..." />
            </SelectTrigger>
            <SelectContent>
              {(field.options || []).map(opt => (
                <SelectItem key={opt} value={opt}>{opt}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        );
      case 'long_text':
        return (
          <Textarea
            value={value}
            onChange={(e) => setEditValue(e.target.value)}
            className="text-sm min-h-[60px]"
            autoFocus
          />
        );
      default:
        return (
          <Input
            value={value}
            onChange={(e) => setEditValue(e.target.value)}
            className="h-7 text-sm"
            autoFocus
            type={field.type === 'email' ? 'email' : field.type === 'url' ? 'url' : field.type === 'number' || field.type === 'currency' ? 'number' : 'text'}
            onKeyDown={(e) => e.key === 'Enter' && (isCompany ? saveCompanyField(field.id) : saveCustomField(field.id))}
          />
        );
    }
  };

  // Section render functions
  const renderContactInfo = () => (
    <>
      {/* Two-column resizable layout (stacks on mobile) */}
      <div className="hidden md:block">
        <ResizablePanelGroup direction="horizontal" className="min-h-[300px] rounded-lg border border-border">
          {/* LEFT BLOCK: Company Info */}
          <ResizablePanel defaultSize={50} minSize={30}>
            <div className="space-y-3 p-3 h-full bg-card overflow-y-auto">
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-1">
                <Building2 className="w-3 h-3" />
                Company Info
              </h3>
              
              {/* Company - LARGER */}
              <div className="group flex items-center gap-2">
                {editingField === 'company' ? (
                  <div className="flex-1 flex gap-1">
                    <Input
                      value={editValue}
                      onChange={(e) => setEditValue(e.target.value)}
                      className="h-9 text-lg font-semibold"
                      autoFocus
                      onKeyDown={(e) => e.key === 'Enter' && saveField('company')}
                    />
                    <Button size="sm" className="h-9 w-9 p-0" onClick={() => saveField('company')}>
                      <Check className="w-4 h-4" />
                    </Button>
                  </div>
                ) : (
                  <>
                    <span 
                      className="text-lg font-semibold text-primary flex-1 cursor-pointer hover:text-primary/80 truncate"
                      onClick={() => onUpdate && startEditing('company', contact.company)}
                    >
                      {contact.company}
                    </span>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                      onClick={() => copyToClipboard(contact.company, 'company')}
                    >
                      {copiedField === 'company' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    </Button>
                  </>
                )}
              </div>

              {/* Website */}
              <div className="group flex items-center gap-2">
                <span className="text-xs text-muted-foreground w-16 flex-shrink-0">Website:</span>
                <div className="flex-1 min-w-0">
                  <InlineEditField
                    value={contact.website || ''}
                    onSave={(value) => onUpdate?.({ website: value })}
                    placeholder="Add website..."
                    type="url"
                    className="text-sm truncate"
                  />
                </div>
                {contact.website && (
                  <>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                      onClick={() => copyToClipboard(contact.website || '', 'website')}
                    >
                      {copiedField === 'website' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    </Button>
                    <a 
                      href={contact.website}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex-shrink-0"
                    >
                      <ExternalLink className="w-3 h-3 text-muted-foreground hover:text-foreground" />
                    </a>
                  </>
                )}
              </div>

              {/* Company Custom Fields - after website, same styling */}
              {activeCompanyFields.length > 0 && contact.company && (
                <>
                  {activeCompanyFields.map(field => {
                    const fieldValue = getCompanyFieldValue(field);
                    const isEditing = editingField === `company_${field.id}`;
                    
                    return (
                      <div key={field.id} className="group flex items-center gap-2">
                        <span className="text-xs text-muted-foreground w-16 flex-shrink-0 truncate" title={field.label}>
                          {field.label}:
                        </span>
                        {isEditing ? (
                          <div className="flex-1 flex gap-1">
                            {renderFieldInput(field, true)}
                            <Button size="sm" className="h-7 w-7 p-0" onClick={() => saveCompanyField(field.id)}>
                              <Check className="w-3 h-3" />
                            </Button>
                          </div>
                        ) : (
                          <>
                            <div className="flex-1 min-w-0">
                              <span 
                                className="text-sm text-foreground cursor-pointer hover:text-primary truncate block"
                                onClick={() => startEditing(`company_${field.id}`, fieldValue)}
                              >
                                {fieldValue || <span className="text-muted-foreground/50">Click to add...</span>}
                              </span>
                            </div>
                            {fieldValue && (
                              <Button
                                variant="ghost"
                                size="sm"
                                className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                                onClick={() => copyToClipboard(fieldValue, `company_${field.id}`)}
                              >
                                {copiedField === `company_${field.id}` ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                              </Button>
                            )}
                          </>
                        )}
                      </div>
                    );
                  })}
                </>
              )}
              {/* Company Summary - inside left block */}
              {contact.company && (
                <AIResearchBox
                  title="Company Summary"
                  content={companyAI.ai_summary}
                  isLoading={isResearching[`company_${contact.company}`] || false}
                  onRefresh={handleRefreshCompanySearch}
                  lastUpdated={companyAI.ai_summary_updated_at}
                  variant="company"
                  buttonLabel="Refresh"
                  maxCollapsedLines={5}
                />
              )}
            </div>
          </ResizablePanel>

          <ResizableHandle withHandle />

          {/* RIGHT BLOCK: Contact Details + Custom Fields */}
          <ResizablePanel defaultSize={50} minSize={30}>
            <div className="space-y-3 p-3 h-full bg-card overflow-y-auto">
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-1">
                <User className="w-3 h-3" />
                Contact Details
              </h3>
              
              {/* Contact Name - BIG and editable */}
              <div className="group flex items-center gap-2">
                {editingField === 'firstName' ? (
                  <div className="flex-1 flex gap-1">
                    <Input
                      value={editValue}
                      onChange={(e) => setEditValue(e.target.value)}
                      className="h-10 text-xl font-bold"
                      autoFocus
                      placeholder="First name"
                      onKeyDown={(e) => e.key === 'Enter' && saveField('firstName')}
                    />
                    <Button size="sm" className="h-10 w-10 p-0" onClick={() => saveField('firstName')}>
                      <Check className="w-4 h-4" />
                    </Button>
                  </div>
                ) : editingField === 'lastName' ? (
                  <div className="flex-1 flex gap-1">
                    <Input
                      value={editValue}
                      onChange={(e) => setEditValue(e.target.value)}
                      className="h-10 text-xl font-bold"
                      autoFocus
                      placeholder="Last name"
                      onKeyDown={(e) => e.key === 'Enter' && saveField('lastName')}
                    />
                    <Button size="sm" className="h-10 w-10 p-0" onClick={() => saveField('lastName')}>
                      <Check className="w-4 h-4" />
                    </Button>
                  </div>
                ) : (
                  <div className="flex-1 flex items-center gap-1">
                    <span 
                      className="text-xl font-bold text-foreground cursor-pointer hover:text-primary"
                      onClick={() => onUpdate && startEditing('firstName', contact.firstName)}
                    >
                      {contact.firstName}
                    </span>
                    <span 
                      className="text-xl font-bold text-foreground cursor-pointer hover:text-primary"
                      onClick={() => onUpdate && startEditing('lastName', contact.lastName)}
                    >
                      {contact.lastName}
                    </span>
                  </div>
                )}
              </div>

              {/* Job Title - under name */}
              <div className="group flex items-center gap-2">
                {editingField === 'jobTitle' ? (
                  <div className="flex-1 flex gap-1">
                    <Input
                      value={editValue}
                      onChange={(e) => setEditValue(e.target.value)}
                      className="h-7 text-sm"
                      autoFocus
                      onKeyDown={(e) => e.key === 'Enter' && saveField('jobTitle')}
                    />
                    <Button size="sm" className="h-7 w-7 p-0" onClick={() => saveField('jobTitle')}>
                      <Check className="w-3 h-3" />
                    </Button>
                  </div>
                ) : (
                  <>
                    <span 
                      className="text-sm text-muted-foreground flex-1 cursor-pointer hover:text-foreground truncate"
                      onClick={() => onUpdate && startEditing('jobTitle', contact.jobTitle)}
                    >
                      {contact.jobTitle || <span className="text-muted-foreground/50">Click to add title...</span>}
                    </span>
                    {contact.jobTitle && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                        onClick={() => copyToClipboard(contact.jobTitle, 'jobTitle')}
                      >
                        {copiedField === 'jobTitle' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      </Button>
                    )}
                  </>
                )}
              </div>

              {/* Phone */}
              <div className="group flex items-center gap-2 p-2 rounded bg-secondary/50 hover:bg-secondary transition-colors">
                <Phone className="w-4 h-4 text-success shrink-0" />
                <div className="flex-1 min-w-0">
                  <InlineEditField
                    value={contact.phone}
                    onSave={(value) => onUpdate?.({ phone: value })}
                    placeholder="Add phone..."
                    type="tel"
                    className="text-sm font-medium"
                  />
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                  onClick={() => copyToClipboard(contact.phone, 'phone')}
                >
                  {copiedField === 'phone' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </Button>
              </div>

              {/* Email */}
              <div className="group flex items-center gap-2 p-2 rounded bg-secondary/50 hover:bg-secondary transition-colors">
                <Mail className="w-4 h-4 text-info shrink-0" />
                <div className="flex-1 min-w-0">
                  <InlineEditField
                    value={contact.email || ''}
                    onSave={(value) => onUpdate?.({ email: value })}
                    placeholder="Add email..."
                    type="email"
                    className="text-sm"
                  />
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                  onClick={() => copyToClipboard(contact.email || '', 'email')}
                >
                  {copiedField === 'email' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-6 px-2 text-xs flex-shrink-0"
                  onClick={openGmail}
                >
                  Gmail
                </Button>
              </div>

              {/* Custom Contact Fields */}
              {activeCustomFields.length > 0 && (
                <div className="space-y-2 pt-2 border-t border-border">
                  <span className="text-xs text-muted-foreground font-medium">Custom Fields</span>
                  {activeCustomFields.map(field => {
                    const fieldValue = getCustomFieldValue(field);
                    const isEditing = editingField === `custom_${field.id}`;
                    
                    return (
                      <div key={field.id} className="group flex items-center gap-2">
                        <span className="text-xs text-muted-foreground w-20 truncate flex-shrink-0" title={field.label}>
                          {field.label}:
                        </span>
                        {isEditing ? (
                          <div className="flex-1 flex gap-1">
                            {renderFieldInput(field, false)}
                            <Button size="sm" className="h-7 w-7 p-0" onClick={() => saveCustomField(field.id)}>
                              <Check className="w-3 h-3" />
                            </Button>
                          </div>
                        ) : (
                          <>
                            <span 
                              className="text-sm text-foreground flex-1 cursor-pointer hover:text-primary truncate"
                              onClick={() => onUpdate && startEditing(`custom_${field.id}`, fieldValue)}
                            >
                              {fieldValue || <span className="text-muted-foreground/50">Click to add...</span>}
                            </span>
                            {fieldValue && (
                              <Button
                                variant="ghost"
                                size="sm"
                                className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                                onClick={() => copyToClipboard(fieldValue, `custom_${field.id}`)}
                              >
                                {copiedField === `custom_${field.id}` ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                              </Button>
                            )}
                          </>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* Linked Contacts - inside Contact Details */}
              <LinkedContacts
                company={contact.company}
                currentContactId={contact.id}
                onSelectContact={onSelectContact}
              />
            </div>
          </ResizablePanel>
        </ResizablePanelGroup>
      </div>

      {/* Mobile stacked layout */}
      <div className="md:hidden space-y-4">
        {/* LEFT BLOCK: Company Info */}
        <div className="space-y-3 p-3 rounded-lg border border-border bg-card">
          <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-1">
            <Building2 className="w-3 h-3" />
            Company Info
          </h3>
          
          {/* Company - LARGER */}
          <div className="group flex items-center gap-2">
            {editingField === 'company' ? (
              <div className="flex-1 flex gap-1">
                <Input
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                  className="h-9 text-lg font-semibold"
                  autoFocus
                  onKeyDown={(e) => e.key === 'Enter' && saveField('company')}
                />
                <Button size="sm" className="h-9 w-9 p-0" onClick={() => saveField('company')}>
                  <Check className="w-4 h-4" />
                </Button>
              </div>
            ) : (
              <>
                <span 
                  className="text-lg font-semibold text-primary flex-1 cursor-pointer hover:text-primary/80 truncate"
                  onClick={() => onUpdate && startEditing('company', contact.company)}
                >
                  {contact.company}
                </span>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                  onClick={() => copyToClipboard(contact.company, 'company')}
                >
                  {copiedField === 'company' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </Button>
              </>
            )}
          </div>

          {/* Website */}
          <div className="group flex items-center gap-2">
            <span className="text-xs text-muted-foreground w-16 flex-shrink-0">Website:</span>
            <div className="flex-1 min-w-0">
              <InlineEditField
                value={contact.website || ''}
                onSave={(value) => onUpdate?.({ website: value })}
                placeholder="Add website..."
                type="url"
                className="text-sm truncate"
              />
            </div>
            {contact.website && (
              <>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                  onClick={() => copyToClipboard(contact.website || '', 'website')}
                >
                  {copiedField === 'website' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </Button>
                <a 
                  href={contact.website}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-shrink-0"
                >
                  <ExternalLink className="w-3 h-3 text-muted-foreground hover:text-foreground" />
                </a>
              </>
            )}
          </div>

          {/* Company Summary */}
          {contact.company && (
            <AIResearchBox
              title="Company Summary"
              content={companyAI.ai_summary}
              isLoading={isResearching[`company_${contact.company}`] || false}
              onRefresh={handleRefreshCompanySearch}
              lastUpdated={companyAI.ai_summary_updated_at}
              variant="company"
              buttonLabel="Refresh"
              maxCollapsedLines={5}
            />
          )}
        </div>

        {/* RIGHT BLOCK: Contact Details + Custom Fields */}
        <div className="space-y-3 p-3 rounded-lg border border-border bg-card">
          <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-1">
            <User className="w-3 h-3" />
            Contact Details
          </h3>
          
          {/* Contact Name - BIG and editable */}
          <div className="group flex items-center gap-2">
            {editingField === 'firstName' ? (
              <div className="flex-1 flex gap-1">
                <Input
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                  className="h-10 text-xl font-bold"
                  autoFocus
                  placeholder="First name"
                  onKeyDown={(e) => e.key === 'Enter' && saveField('firstName')}
                />
                <Button size="sm" className="h-10 w-10 p-0" onClick={() => saveField('firstName')}>
                  <Check className="w-4 h-4" />
                </Button>
              </div>
            ) : editingField === 'lastName' ? (
              <div className="flex-1 flex gap-1">
                <Input
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                  className="h-10 text-xl font-bold"
                  autoFocus
                  placeholder="Last name"
                  onKeyDown={(e) => e.key === 'Enter' && saveField('lastName')}
                />
                <Button size="sm" className="h-10 w-10 p-0" onClick={() => saveField('lastName')}>
                  <Check className="w-4 h-4" />
                </Button>
              </div>
            ) : (
              <div className="flex-1 flex items-center gap-1">
                <span 
                  className="text-xl font-bold text-foreground cursor-pointer hover:text-primary"
                  onClick={() => onUpdate && startEditing('firstName', contact.firstName)}
                >
                  {contact.firstName}
                </span>
                <span 
                  className="text-xl font-bold text-foreground cursor-pointer hover:text-primary"
                  onClick={() => onUpdate && startEditing('lastName', contact.lastName)}
                >
                  {contact.lastName}
                </span>
              </div>
            )}
          </div>

          {/* Job Title - under name */}
          <div className="group flex items-center gap-2">
            {editingField === 'jobTitle' ? (
              <div className="flex-1 flex gap-1">
                <Input
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                  className="h-7 text-sm"
                  autoFocus
                  onKeyDown={(e) => e.key === 'Enter' && saveField('jobTitle')}
                />
                <Button size="sm" className="h-7 w-7 p-0" onClick={() => saveField('jobTitle')}>
                  <Check className="w-3 h-3" />
                </Button>
              </div>
            ) : (
              <>
                <span 
                  className="text-sm text-muted-foreground flex-1 cursor-pointer hover:text-foreground truncate"
                  onClick={() => onUpdate && startEditing('jobTitle', contact.jobTitle)}
                >
                  {contact.jobTitle || <span className="text-muted-foreground/50">Click to add title...</span>}
                </span>
                {contact.jobTitle && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                    onClick={() => copyToClipboard(contact.jobTitle, 'jobTitle')}
                  >
                    {copiedField === 'jobTitle' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                  </Button>
                )}
              </>
            )}
          </div>

          {/* Phone */}
          <div className="group flex items-center gap-2 p-2 rounded bg-secondary/50 hover:bg-secondary transition-colors">
            <Phone className="w-4 h-4 text-success shrink-0" />
            <div className="flex-1 min-w-0">
              <InlineEditField
                value={contact.phone}
                onSave={(value) => onUpdate?.({ phone: value })}
                placeholder="Add phone..."
                type="tel"
                className="text-sm font-medium"
              />
            </div>
            <Button
              variant="ghost"
              size="sm"
              className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
              onClick={() => copyToClipboard(contact.phone, 'phone')}
            >
              {copiedField === 'phone' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
            </Button>
          </div>

          {/* Email */}
          <div className="group flex items-center gap-2 p-2 rounded bg-secondary/50 hover:bg-secondary transition-colors">
            <Mail className="w-4 h-4 text-info shrink-0" />
            <div className="flex-1 min-w-0">
              <InlineEditField
                value={contact.email || ''}
                onSave={(value) => onUpdate?.({ email: value })}
                placeholder="Add email..."
                type="email"
                className="text-sm"
              />
            </div>
            <Button
              variant="ghost"
              size="sm"
              className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
              onClick={() => copyToClipboard(contact.email || '', 'email')}
            >
              {copiedField === 'email' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="h-6 px-2 text-xs flex-shrink-0"
              onClick={openGmail}
            >
              Gmail
            </Button>
          </div>

          {/* Custom Contact Fields */}
          {activeCustomFields.length > 0 && (
            <div className="space-y-2 pt-2 border-t border-border">
              <span className="text-xs text-muted-foreground font-medium">Custom Fields</span>
              {activeCustomFields.map(field => {
                const fieldValue = getCustomFieldValue(field);
                const isEditing = editingField === `custom_${field.id}`;
                
                return (
                  <div key={field.id} className="group flex items-center gap-2">
                    <span className="text-xs text-muted-foreground w-20 truncate flex-shrink-0" title={field.label}>
                      {field.label}:
                    </span>
                    {isEditing ? (
                      <div className="flex-1 flex gap-1">
                        {renderFieldInput(field, false)}
                        <Button size="sm" className="h-7 w-7 p-0" onClick={() => saveCustomField(field.id)}>
                          <Check className="w-3 h-3" />
                        </Button>
                      </div>
                    ) : (
                      <>
                        <span 
                          className="text-sm text-foreground flex-1 cursor-pointer hover:text-primary truncate"
                          onClick={() => onUpdate && startEditing(`custom_${field.id}`, fieldValue)}
                        >
                          {fieldValue || <span className="text-muted-foreground/50">Click to add...</span>}
                        </span>
                        {fieldValue && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 flex-shrink-0"
                            onClick={() => copyToClipboard(fieldValue, `custom_${field.id}`)}
                          >
                            {copiedField === `custom_${field.id}` ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                          </Button>
                        )}
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          )}

          {/* Linked Contacts - inside Contact Details (mobile) */}
          <LinkedContacts
            company={contact.company}
            currentContactId={contact.id}
            onSelectContact={onSelectContact}
          />
        </div>
      </div>
    </>
  );

  const renderHistory = () => (
    <ContactHistoryBar contactId={contact.id} />
  );

  const renderTargetedResearch = () => (
    <Collapsible defaultOpen={sectionExpandedDefaults?.targeted_research ?? false}>
      <CollapsibleTrigger asChild>
        <Button variant="ghost" size="sm" className="w-full justify-between p-2 h-auto hover:bg-muted/50">
          <span className="text-sm font-medium">Targeted Research</span>
          <ChevronDown className="w-4 h-4 transition-transform data-[state=open]:rotate-180" />
        </Button>
      </CollapsibleTrigger>
      <CollapsibleContent className="pt-2">
        <AIResearchBox
          title=""
          content={companyAI.ai_custom_research}
          isLoading={isResearching[`custom_${contact.company}`] || false}
          onRefresh={handleRefreshCustomResearch}
          lastUpdated={companyAI.ai_custom_updated_at}
          variant="custom"
          buttonLabel="Run Research"
          maxCollapsedLines={5}
          disabled={targetedResearchDisabled}
          disabledReason={getDisabledReason()}
        />
      </CollapsibleContent>
    </Collapsible>
  );

  const renderPersona = () => (
    <Collapsible defaultOpen={sectionExpandedDefaults?.persona ?? false}>
      <CollapsibleTrigger asChild>
        <Button variant="ghost" size="sm" className="w-full justify-between p-2 h-auto hover:bg-muted/50">
          <span className="text-sm font-medium">Persona</span>
          <ChevronDown className="w-4 h-4 transition-transform data-[state=open]:rotate-180" />
        </Button>
      </CollapsibleTrigger>
      <CollapsibleContent className="pt-2">
        <AIResearchBox
          title=""
          content={contactPersona}
          isLoading={isResearching[`persona_${contact.id}`] || false}
          onRefresh={handleRefreshPersona}
          lastUpdated={personaUpdatedAt}
          variant="persona"
          buttonLabel="Refresh"
          maxCollapsedLines={5}
        />
      </CollapsibleContent>
    </Collapsible>
  );

  const renderAIScript = () => (
    <Collapsible defaultOpen={sectionExpandedDefaults?.ai_script ?? false}>
      <CollapsibleTrigger asChild>
        <Button variant="ghost" size="sm" className="w-full justify-between p-2 h-auto hover:bg-muted/50">
          <span className="text-sm font-medium">AI Script</span>
          <ChevronDown className="w-4 h-4 transition-transform data-[state=open]:rotate-180" />
        </Button>
      </CollapsibleTrigger>
      <CollapsibleContent className="pt-2 space-y-2">
        <div className="flex items-center justify-between">
          <ScriptSelector 
            value={selectedScriptId} 
            onChange={setSelectedScriptId}
            disabled={isGeneratingScript || isAutoGenerating}
          />
        </div>
        <AIResearchBox
          title=""
          content={aiScript}
          isLoading={isGeneratingScript}
          onRefresh={() => handleGenerateScript()}
          lastUpdated={aiScriptUpdatedAt}
          variant="script"
          buttonLabel="Regenerate"
          maxCollapsedLines={8}
        />
      </CollapsibleContent>
    </Collapsible>
  );

  const renderStaticScript = () => (
    <Collapsible defaultOpen={sectionExpandedDefaults?.static_script ?? false}>
      <CollapsibleTrigger asChild>
        <Button variant="ghost" size="sm" className="w-full justify-between p-2 h-auto hover:bg-muted/50">
          <span className="text-sm font-medium">Static Script</span>
          <ChevronDown className="w-4 h-4 transition-transform data-[state=open]:rotate-180" />
        </Button>
      </CollapsibleTrigger>
      <CollapsibleContent className="pt-2">
        <StaticScriptCard contact={contact} />
      </CollapsibleContent>
    </Collapsible>
  );

  const sectionRenderers: Record<SectionKey, () => React.ReactNode> = {
    contact_info: renderContactInfo,
    history: renderHistory,
    targeted_research: renderTargetedResearch,
    persona: renderPersona,
    ai_script: renderAIScript,
    static_script: renderStaticScript,
  };

  return (
    <div className="space-y-4">
      {/* Callback indicator - at top (always first) */}
      {contact.status === 'callback' && contact.callbackDate && (
        <div className="p-2 rounded bg-[hsl(var(--callback-light))] border border-[hsl(var(--callback))]">
          <p className="text-sm font-medium text-foreground">
            📞 Callback: {formatCallbackDate(contact.callbackDate)}
          </p>
        </div>
      )}

      {/* Render sections in order */}
      {sectionOrder.map((sectionKey) => (
        <React.Fragment key={sectionKey}>
          {sectionRenderers[sectionKey]?.()}
        </React.Fragment>
      ))}

      {/* Auto-generate progress indicator */}
      {isAutoGenerating && autoGenProgress && (
        <div className="flex items-center gap-2 p-3 rounded-lg bg-primary/10 border border-primary/20">
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
          <span className="text-sm text-primary">{autoGenProgress}</span>
        </div>
      )}

      {/* Danger Zone - Hidden by default (always at bottom) */}
      {onDelete && (
        <Collapsible className="mt-4 pt-4 border-t border-destructive/20">
          <CollapsibleTrigger asChild>
            <Button variant="ghost" size="sm" className="w-full text-muted-foreground hover:text-destructive text-xs">
              <ChevronDown className="w-3 h-3 mr-1" />
              Danger Zone
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent className="mt-2 p-3 rounded border border-destructive/20 bg-destructive/5">
            <p className="text-xs text-muted-foreground mb-2">
              Permanently delete this contact and all associated history. This cannot be undone.
            </p>
            <Button 
              variant="destructive" 
              size="sm"
              className="w-full"
              onClick={() => setShowDeleteConfirm(true)}
            >
              <Trash2 className="w-3 h-3 mr-1" />
              Delete Contact Permanently
            </Button>
          </CollapsibleContent>
        </Collapsible>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteConfirm} onOpenChange={setShowDeleteConfirm}>
        <AlertDialogContent className="bg-card border-border">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Contact Permanently?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete <strong>{contact.firstName} {contact.lastName}</strong> and all their history, notes, and data. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={async () => {
                if (onDelete) {
                  await onDelete(contact.id);
                }
                setShowDeleteConfirm(false);
              }}
            >
              Delete Permanently
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

    </div>
  );
}
